//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_register
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public emp_register()
        {
            this.policy_request_details = new HashSet<policy_request_details>();
        }
    
        public int EmpId { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> Joindate { get; set; }
        public Nullable<double> Salary { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string PolicyStatus { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public int policies_PolicyId { get; set; }
    
        public virtual policies policies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<policy_request_details> policy_request_details { get; set; }
    }
}
