//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Care.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_MedicalCareEntities1 : DbContext
    {
        public DB_MedicalCareEntities1()
            : base("name=DB_MedicalCareEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_login> admin_login { get; set; }
        public virtual DbSet<company_details> company_details { get; set; }
        public virtual DbSet<emp_register> emp_register { get; set; }
        public virtual DbSet<hospital_info> hospital_info { get; set; }
        public virtual DbSet<policies> policies { get; set; }
        public virtual DbSet<policies_on_employees> policies_on_employees { get; set; }
        public virtual DbSet<policy_approval_details> policy_approval_details { get; set; }
        public virtual DbSet<policy_request_details> policy_request_details { get; set; }
        public virtual DbSet<policy_total_description> policy_total_description { get; set; }
    }
}
