//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy_request_details
    {
        public int RequestId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> Policyname { get; set; }
        public Nullable<double> PolicyAmount { get; set; }
        public Nullable<double> EMI { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Status { get; set; }
    
        public virtual emp_register emp_register { get; set; }
        public virtual company_details company_details { get; set; }
    }
}
