//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policies
    {
        public int PolicyId { get; set; }
        public Nullable<double> PolicyName { get; set; }
        public Nullable<double> PolicyDesc { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> EMI { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Medicalid { get; set; }
    
        public virtual company_details company_details { get; set; }
    }
}
