//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policy_total_description
    {
        public int PTDId { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public string PolicyName { get; set; }
        public string PolicyDes { get; set; }
        public Nullable<double> PolicyAmount { get; set; }
        public Nullable<double> EMI { get; set; }
        public Nullable<int> PolicyDurationInMonth { get; set; }
        public string CompanyName { get; set; }
        public string Medicalid { get; set; }
    }
}
