export const MenuItem = {
    items: [
        {
            id: "general",
            title: "General",
            type: "group",
            icon: "icon-navigation",
            children: [
                {
                    id: "dashboard",
                    title: "Dashboard",
                    type: "item",
                    url: "/",
                    icon: "feather icon-home",
                    role: [2, 3, 6, 7, 10],
                },
                {
                    id: "orders",
                    title: "Orders",
                    type: "item",
                    url: "/orders",
                    icon: "feather icon-download",
                    role: [2, 3, 6, 7, 10],
                },
                {
                    id: "products",
                    title: "Products",
                    type: "collapse",
                    icon: "feather icon-tag",
                    role: [2, 3, 6, 7],
                    children: [
                        {
                            id: "product",
                            title: "Product Management",
                            type: "item",
                            url: "/products/product",
                            role: [2, 3, 7, 6],
                        },
                        {
                            id: "product-type",
                            title: "Product Type",
                            type: "item",
                            url: "/products/product-type",
                            role: [2, 3, 6, 7],
                        },
                        {
                            id: "category",
                            title: "Category",
                            type: "item",
                            url: "/products/category",
                            role: [2, 3],
                        },
                        {
                            id: "carrier",
                            title: "Carrier",
                            type: "item",
                            url: "/products/carrier",
                            role: [2, 3],
                        },
                    ],
                },
                {
                    id: "billing",
                    title: "Billing",
                    type: "collapse",
                    icon: "feather icon-credit-card",
                    role: [2, 3, 6, 7],
                    children: [
                        {
                            id: "outstanding-invoices",
                            title: "Outstanding Invoices",
                            type: "item",
                            url: "/billing/outstanding-invoices",
                            role: [2, 3, 6, 7],
                        },
                        {
                            id: "payment-methods",
                            title: "Payment Methods",
                            type: "item",
                            url: "/billing/payment-methods",
                            role: [2, 3, 6],
                        },
                        {
                            id: "transaction-history",
                            title: "Transaction History",
                            type: "item",
                            url: "/billing/transaction-history",
                            role: [2, 3, 6],
                        },
                    ],
                },
                {
                    id: "sites",
                    title: "Sites",
                    type: "collapse",
                    icon: "feather icon-activity",
                    role: [2, 6],
                    children: [
                        {
                            id: "site",
                            title: "Site Management",
                            type: "item",
                            url: "/sites/site",
                            role: [6],
                        },
                        {
                            id: "listsites",
                            title: "List Sites",
                            type: "item",
                            url: "/sites/list-sites",
                            role: [2],
                        },
                    ],
                },
                {
                    id: "chart",
                    title: "Charts",
                    type: "collapse",
                    icon: "feather icon-charts-2",
                    role: [2, 3],
                    children: [
                        {
                            id: "Admin dashboard",
                            title: "Admin dashboard",
                            type: "item",
                            url: "/chart/index",
                            role: [2, 3],
                        },
                        {
                            id: "seller dashboard",
                            title: "Seller dashboard",
                            type: "item",
                            url: "/chart/newIndex",
                            role: [2, 3],
                        },
                        {
                            id: "transaction-history",
                            title: "Transaction History",
                            type: "item",
                            url: "/billing/transaction-history",
                            role: [2, 3],
                        },
                    ],
                },
            ],
        },
    ],
};
